### PR TITLE
feat: allow custom message

### LINKED ISSUE #33: Allow custom comments
Allow user to make custom comments, so that if user wants to notify multiple artifacts, one can differentiate between the two artifacts

### PR DESCRIPTION
**Pull request by Naturalclar**
Closes #33
added feature to allow custom message on github

### CODE REVIEW

**Comment by Naturalclar** [comment]
Artifact can be viewed here:
https://110-173251107-gh.circle-artifacts.com/0/home/circleci/app/example/artifact/index.html

**Comment by Naturalclar** [comment]
Artifact can be viewed here:
https://110-173251107-gh.circle-artifacts.com/0/home/circleci/app/example/artifact/index.html

**Comment by Naturalclar** [comment]
Artifact can be viewed here: :
https://111-173251107-gh.circle-artifacts.com/0/home/circleci/app/example/artifact/index.html

**Comment by Naturalclar** [comment]
Custom Message:
https://111-173251107-gh.circle-artifacts.com/0/home/circleci/app/example/artifact/index.html

**Comment by kowalcj0** [comment]
Hi @Naturalclar 

Is there a chance to have the same functionality added to Slack notifications?

Thanks

**Comment by Naturalclar** [comment]
@kowalcj0 Sure! I've made an issue for it #41
I can work on it when I get free time, or I'm willing to accept pull requests 😄

**Pull request merged**
