### PR TITLE
Feature - support custom Slack notification message

### PR DESCRIPTION
**Pull request by kowalcj0**
This is similar to https://github.com/moxci/moxci/pull/34 but adds option to set custom Slack notification message.

### CODE REVIEW

**Comment by kowalcj0** [comment]
Hi @Naturalclar 

This feature can come in handy e.g. when your team runs multiple workflows on CircleCi that produce various artifacts. 
Without this option it's not possible to tell which Slack notification link points to which report/artifact.

image

**Review by Naturalclar — CHANGES_REQUESTED** [review]
@kowalcj0 
Thank you so much for working on this!
It looks good!
I'm wondering if slack_message should be made as a separate option from regular `message`.
I feel like it would be tedious to set message for both github PR comment and slack notification if one were to use both.
Would you mind setting the code so that `-m` option will set message for both github pr comment and slack message?

**Comment by kowalcj0** [comment]
Thanks @Naturalclar 
Sure thing that it can be done using just one `message` option, but then users would receive the same message to both Slack and Github. Not sure if that would work for all users.
If you're happy with that, then I can change the code.

**Comment by Naturalclar** [comment]
@kowalcj0 
>Not sure if that would work for all users.

True. I think it would be nice if the default behavior is for `-m` to work for both github and slack. If user choses to use a separate message for slack, then that user can use the `-s` option to specifically chose message for slack notification. What do you think?

**Comment by kowalcj0** [comment]
Sounds like a plan. Will work on it now :)

**Comment by kowalcj0** [comment]
done @Naturalclar  :)

**Review by Naturalclar — APPROVED** [review]
@kowalcj0 Awesome! thank you so much!

**Comment by Naturalclar** [comment]
@kowalcj0 published 0.1.2 :tada:

**Comment by kowalcj0** [comment]
Thank you @Naturalclar 
My fist success of the day :)

**Pull request merged**
